name: pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: checkpot
        run: echo "aca va un checkout"
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0 
      - name: ls -la
        run: ls -la
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - name: test eslint
        run: npm run eslint